[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "--cov=promoklocki_notifier"
testpaths = [
    "tests",
]

[[tool.mypy.overrides]]
mypy_path = "src"
module = "requests.*,psycopg2.*,bs4.*"
ignore_missing_imports = true
